# Taskfile configuration
# Path: tasks/logical/setup.yml

version: "3"
tasks:
  setup:
    desc: Set up the project
    cmds:
      - task: deps:install
      - task: lefthook:install
      - task: typecheck
      - task: build
      - task: lint:check
      - task: test:coverage
