# Taskfile configuration
# Path: tasks/tools/markdownlint.yml

version: "3"
tasks:
  markdownlint:check:
    desc: Lint Markdown files
    cmds:
      - markdownlint-cli2 "**/*.md"
    sources:
      - "**/*.md"
      - ".markdownlint.json"
      - ".markdownlint-cli2.jsonc"
  markdownlint:fix:
    desc: Lint and fix Markdown files
    cmds:
      - markdownlint-cli2 --fix "**/*.md"
    sources:
      - "**/*.md"
      - ".markdownlint.json"
      - ".markdownlint-cli2.jsonc"
  markdownlint:check:watch:
    desc: Lint Markdown files in watch mode
    cmds:
      - task: markdownlint:check
    sources:
      - "**/*.md"
      - ".markdownlint.json"
      - ".markdownlint-cli2.jsonc"
    watch: true
  markdownlint:fix:watch:
    desc: Lint and fix Markdown files in watch mode
    cmds:
      - task: markdownlint:fix
    sources:
      - "**/*.md"
      - ".markdownlint.json"
      - ".markdownlint-cli2.jsonc"
    watch: true
