# Taskfile configuration
# Path: tasks/tools/shell.yml

version: "3"
tasks:
  shell:
    aliases:
      - $
    desc: Launch shell or execute command in this directory
    cmds:
      - |-
        if [ $# -eq 0 ]; then
          echo "ğŸš Launching shell in $PWD"
          exec $SHELL
        else
          echo "ğŸš€ Executing: $*"
          exec "$@"
        fi
